server:
  port: 8081

spring:
  application:
    name: ms_users
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          multiplier: 2
          max-interval: 10s
        default-requeue-rejected: false
        acknowledge-mode: auto
        prefetch: 10
    template:
      retry:
        enabled: true
        initial-interval: 1s
        max-attempts: 3
        multiplier: 2