package az.ingress.model.constants;

public interface QueueConstants {
    String PUBLISHER_QUEUE = "PUBLISHER_QUEUE";
    String PUBLISHER_DLQ = "PUBLISHER_DLQ";
    String PUBLISHER_EXCHANGE = "PUBLISHER_EXCHANGE";
    String PUBLISHER_DLQ_EXCHANGE = "PUBLISHER_DLQ_EXCHANGE";
    String PUBLISHER_ROUTING_KEY = "PUBLISHER_ROUTING_KEY";
    String PUBLISHER_DLQ_ROUTING_KEY = "PUBLISHER_DLQ_ROUTING_KEY";

}
